server:
  port: 9999
spring:

  datasource:
    url: jdbc:mysql://${db.host:localhost}:${db.port:3306}/${db.name:jpa}?useSSL=${db.useSSL:false}&allowPublicKeyRetrieval=${db.allowPublicKeyRetrieval:true}
    username: ${db.username:root}
    password: ${db.password:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: mysql
  jpa:
    show-sql: true
    properties:
      hibernate:
        ejb:
          interceptor: com.boutiqaat.jpa.repo.betterpaging.PageableQueriesInterceptor
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
      
      
 